In [ ]:
import pandas as pd
from ytmusicapi import YTMusic

def call(row):
    ytmusic = YTMusic()

    param = row['Artista'] + ' ' + row['Musica']
    print(param)
    result = ytmusic.search(param, filter='songs')

    if len(result) > 0:
        return result[0]['videoId']

df = pd.read_csv('./data/500+.csv')


newdf = df.groupby(['Artista', 'Musica', 'Observacao'], dropna=False)
newdf = newdf.size().reset_index(name='size').drop(columns='size')
newdf["SongID"] = (
    newdf["Artista"].astype(str).str.strip() + " — " +
    newdf["Musica"].astype(str).str.strip() + " — " +
    newdf["Observacao"].astype(str).str.strip()
)
newdf['YT'] = newdf.apply(call, axis=1)
newdf

newdf.to_csv('youtube.csv', index=False)

10,000 Maniacs More Than This
10cc I'm Not in Love
10cc Rubber Bullets
3 Doors Down Here Without You
3 Doors Down Kryptonite
38 Special Back Where You Belong
38 Special Hold On Loosely
4 Non Blondes What's Up?
A Flock of Seagulls I Ran (So Far Away)
A Flock of Seagulls I Ran (So Far Away)
AC/DC Are You Ready
AC/DC Baby, Please Don't Go
AC/DC Back in Black
AC/DC Black Ice
AC/DC Dirty Deeds Done Dirt Cheap
AC/DC For Those About to Rock (We Salute You)
AC/DC Hard as a Rock
AC/DC Hells Bells
AC/DC Highway to Hell
AC/DC It's a Long Way to the Top (If You Wanna Wanna Rock 'N' Roll)
AC/DC Jailbreak
AC/DC Moneytalks
AC/DC Realize
AC/DC Rock 'N Roll Train
AC/DC Rock 'n' Roll Singer
AC/DC Rock and Roll Ain't Noise Pollution
AC/DC Shoot to Thrill
AC/DC Shot in the Dark
AC/DC T.N.T.
AC/DC T.N.T.
AC/DC Thunderstruck
AC/DC You Shook Me All Night Long
Accept Balls to the Wall
Aerosmith Amazing
Aerosmith Angel
Aerosmith Back in the Saddle
Aerosmith Come Together
Aerosmith Crazy
Aerosmith Cryin'
Aerosmith Deuces Are Wild
Aerosmith Devil's Got a New Disguise
Aerosmith Draw the Line
Aerosmith Dream On
Aerosmith Dude (Looks Like a Lady)
Aerosmith Eat the Rich
Aerosmith Falling in Love (Is Hard on the Knees)
Aerosmith Fly Away from Here
Aerosmith Full Circle
Aerosmith Hole in My Soul
Aerosmith I Don't Want to Miss a Thing
Aerosmith I'm Down
Aerosmith Jaded
Aerosmith Janie's Got a Gun
Aerosmith Kings and Queens
Aerosmith Last Child
Aerosmith Livin' on the Edge
Aerosmith Love in an Elevator
Aerosmith Mama Kin
Aerosmith Mia
Aerosmith No More No More
Aerosmith Pink
Aerosmith Rag Doll
Aerosmith Remember (Walking in the Sand)
Aerosmith Same Old Song and Dance
Aerosmith Sweet Emotion
Aerosmith The Other Side
Aerosmith Train Kept A-Rollin'
Aerosmith Walk This Way
Aerosmith What Could Have Been Love
Aerosmith What It Takes
Al Stewart Year of the Cat
Alabama Shakes Always Alright
Alabama Shakes Hold On
Alanis Morissette Guardian
Alanis Morissette You Oughta Know
Alice Cooper Be My Lover
Alice Cooper Billion Dollar Babies
Alice Cooper Clones (We're All)
Alice Cooper Elected
Alice Cooper Feed My Frankenstein
Alice Cooper Generation Landslide
Alice Cooper Hey Stoopid
Alice Cooper How You Gonna See Me Now
Alice Cooper I Never Cry
Alice Cooper I'm Eighteen
Alice Cooper No More Mr. Nice Guy
Alice Cooper Perfect
Alice Cooper Poison
Alice Cooper School's Out
Alice Cooper Under My Wheels
Alice Cooper You and Me
Alice in Chains Heaven Beside You
Alice in Chains I Stay Away
Alice in Chains Man in the Box
Alice in Chains No Excuses
Alice in Chains Them Bones
Alice in Chains Voices
Alice in Chains We Die Young
Alice in Chains Would?
Alice in Chains Your Decision
Alphaville Big in Japan
Alphaville Forever Young
Alter Bridge Broken Wings
America A Horse with No Name
America Sister Golden Hair
America Ventura Highway
America You Can Do Magic
Amy Winehouse Valerie
Anathema Untouchable Part 1
Angra Lisbon
Angra Rebirth
April Wine Sign of the Gypsy Queen
April Wine You Could Have Been A Lady
Arc Angels Sent by Angels
Arcadia Election Day
Arctic Monkeys Do I Wanna Know?
Arctic Monkeys Fake Tales of San Francisco
Arctic Monkeys Fluorescent Adolescent
Arctic Monkeys R U Mine?
Aretha Franklin Chain of Fools
Aretha Franklin Respect
Argent Time of the Season
Armored Dawn Ragnarok
Asia Heat of the Moment
Asia Only Time Will Tell
Asia Voice of America
Audioslave Be Yourself
Audioslave Cochise
Audioslave Like a Stone
Audioslave Original Fire
Audioslave Show Me How to Live
Autograph Turn Up the Radio
B. B. King Into The Night
B. B. King My Lucille
B. B. King The Thrill Is Gone
B. J. Thomas Raindrops Keep Fallin' on My Head
Bachman–Turner Overdrive Down the Road
Bachman–Turner Overdrive Down to the Line
Bachman–Turner Overdrive Down, Down
Bachman–Turner Overdrive Hey You
Bachman–Turner Overdrive Hold Back the Water
Bachman–Turner Overdrive Let It Ride
Bachman–Turner Overdrive Takin' Care of Business
Bachman–Turner Overdrive You Ain't Seen Nothing Yet
Bad Company Bad Company
Bad Company Can't Get Enough
Bad Company Feel Like Makin' Love
Bad Company Live For The Music
Bad Company Ready for Love
Bad Company Rock 'n' Roll Fantasy
Bad Company Shooting Star
Bad Religion 21st Century (Digital Boy)
Bad Religion A Walk
Bad Religion American Jesus
Bad Religion Fuck You
Bad Religion Infected
Bad Religion New America
Bad Religion Sorrow
Badfinger Baby Blue
Badfinger Day After Day
Badfinger No Matter What
Barão Vermelho O Poeta Está Vivo
Barão Vermelho Pedra, Flor e Espinho
Bauhaus Bela Lugosi's Dead
Bauhaus Ziggy Stardust
Beastie Boys No Sleep till Brooklyn
Beck Loser
Bee Gees I Started a Joke
Bee Gees Massachusetts
Bee Gees Words
Ben E. King Stand by Me
Big Audio Dynamite E=MC2
Big Brother and the Holding Company Ball And Chain
Big Brother and the Holding Company Bye, Bye Baby
Big Brother and the Holding Company Down on Me
Big Brother and the Holding Company Down on Me
Big Brother and the Holding Company I Need a Man to Love
Big Brother and the Holding Company Piece of My Heart
Big Brother and the Holding Company Summertime
Big Country In a Big Country
Big Country Look Away
Bill Haley & His Comets Rock Around the Clock
Bill Withers Lean on Me
Billy Idol Cradle of Love
Billy Idol Dancing with Myself
Billy Idol Eyes Without a Face
Billy Idol Flesh for Fantasy
Billy Idol L.A. Woman
Billy Idol Mony Mony
Billy Idol Rebel Yell
Billy Idol Sweet Sixteen
Billy Idol White Wedding
Billy Joel Uptown Girl
Billy Squier The Stroke
Biquini Cavadão Zé Ninguém
Black Label Society Blood is Thicker Than Water
Black Label Society The Last Goodbye
Black Sabbath Black Sabbath
Black Sabbath Changes
Black Sabbath Children of the Grave
Black Sabbath Electric Funeral
Black Sabbath God Is Dead?
Black Sabbath Heaven and Hell
Black Sabbath Iron Man
Black Sabbath N.I.B.
Black Sabbath Paranoid
Black Sabbath Sabbath Bloody Sabbath
Black Sabbath Snowblind
Black Sabbath Supernaut
Black Sabbath The Wizard
Black Sabbath War Pigs
Black Sabbath War Pigs
Blackberry Smoke Rock and Roll Again
Blackfoot Fly Away
Blind Faith Sea Of Joy
Blind Guardian Surfin' U.S.A.
Blind Melon No Rain
Blink-182 All the Small Things
Blink-182 Darkside
Blink-182 Edging
Bliss I Hear You Call
Blondie Call Me
Blondie Dreaming
Blondie Hanging on the Telephone
Blondie Heart of Glass
Blondie Maria
Blondie One Way or Another
Blood, Sweat & Tears And When I Die
Blood, Sweat & Tears Go Down Gamblin
Blood, Sweat & Tears Spinning Wheel
Blood, Sweat & Tears You've Made Me So Very Happy
Blue Öyster Cult (Don't Fear) The Reaper
Blue Öyster Cult Burnin' for You
Blue Öyster Cult Godzilla
Blue Öyster Cult Joan Crawford
Blues Traveler Run-Around
Blur Song 2
Bo Diddley Hey! Bo Diddley
Bob Dylan All Along the Watchtower
Bob Dylan Blowin' in the Wind
Bob Dylan Hurricane
Bob Dylan Jokerman
Bob Dylan Just Like a Woman
Bob Dylan Knockin' on Heaven's Door
Bob Dylan Lay Lady Lay
Bob Dylan Like a Rolling Stone
Bob Dylan Mr. Tambourine Man
Bob Seger Turn the Page
Bob Seger & the Silver Bullet Band Against the Wind
Bob Seger & the Silver Bullet Band Hollywood Nights
Bob Seger & the Silver Bullet Band Night Moves
Bob Seger & the Silver Bullet Band Still the Same
Bob Seger & the Silver Bullet Band The Fire Inside
Bon Jovi Always
Bon Jovi Bad Medicine
Bon Jovi Blood on Blood
Bon Jovi Born to Be My Baby
Bon Jovi Have a Nice Day
Bon Jovi I'll Be There for You
Bon Jovi In These Arms
Bon Jovi It's My Life
Bon Jovi Keep the Faith
Bon Jovi Let It Rock
Bon Jovi Livin' on a Prayer
Bon Jovi Misunderstood
Bon Jovi Runaway
Bon Jovi These Days
Bon Jovi Wanted Dead or Alive
Bon Jovi You Give Love a Bad Name
Booker T. & the M.G.'s Green Onions
Boston Don't Look Back
Boston More Than a Feeling
Boston Peace of Mind
Boston Rock and Roll Band
Bread The Guitar Man
Brian Setzer Summertime Blues
Bruce Dickinson All the Young Dudes
Bruce Dickinson Chemical Wedding
Bruce Dickinson Tears of the Dragon
Bruce Hornsby and the Range The Way It Is
Bruce Springsteen Because the Night
Bruce Springsteen Because the Night
Bruce Springsteen Born in the U.S.A.
Bruce Springsteen Born to Run
Bruce Springsteen Dancing in the Dark
Bruce Springsteen Glory Days
Bruce Springsteen Human Touch
Bruce Springsteen Hungry Heart
Bruce Springsteen I'm Goin' Down
Bruce Springsteen Letter to You
Bruce Springsteen Streets of Philadelphia
Bryan Ferry Don't Stop the Dance
Buddy Guy Mustang Sally
Buddy Holly Oh, Boy!
Buddy Holly Peggy Sue
Buffalo Springfield For What It's Worth
Bush Machinehead
CPM 22 Um Minuto para o Fim do Mundo
Cake Never There
Camisa de Vênus Simca Chambord
Candlebox Far Behind
Canned Heat On the Road Again
Capital Inicial Fátima
Capital Inicial Natasha
Capital Inicial O Mundo
Capital Inicial O Passageiro
Carl Perkins Blue Suede Shoes
Carly Simon You're So Vain
Carole King It's Too Late
Cat Mother and The All Night Newsboys Good Old Rock´n Roll
Cat Stevens Father and Son
Cat Stevens Morning Has Broken
Cat Stevens Wild World
Cazuza Exagerado
Charlie Brown Jr. Confisco
Charlie Brown Jr. Lugar ao sol
Charlie Brown Jr. Zoio D Lula
Charlie Daniels Band The Devil Went Down to Georgia
Chicago 25 or 6 to 4
Chicago Colour My World
Chicago If You Leave Me Now
Chicago Questions 67 and 68
Chicago Saturday in the Park
Chickenfoot Something Going Wrong
Chris Isaak Wicked Game
Chris Rea The Road to Hell
Chubby Checker Let's Twist Again
Chubby Checker The Twist
Chuck Berry Johnny B. Goode
Chuck Berry Roll Over Beethoven
Chuck Berry Sweet Little Sixteen
Coldplay Clocks
Coldplay Talk
Coldplay The Hardest Part
Coldplay The Scientist
Coldplay Viva la Vida
Coldplay Yellow
Colin Hay Into my Life
Collective Soul December
Collective Soul Shine
Concrete Blonde Heal It Up
Counting Crows Mr. Jones
Coverdale and Page Shake My Tree
Coverdale and Page Take Me For A Little While
Crash Test Dummies Mmm Mmm Mmm Mmm
Cream Cross Road Blues
Cream I Feel Free
Cream Sunshine of Your Love
Cream White Room
Creed My Sacrifice
Creed One Last Breath
Creed Rain
Creedence Clearwater Revival Bad Moon Rising
Creedence Clearwater Revival Born on the Bayou
Creedence Clearwater Revival Fortunate Son
Creedence Clearwater Revival Good Golly Miss Molly
Creedence Clearwater Revival Green River
Creedence Clearwater Revival Have You Ever Seen the Rain?
Creedence Clearwater Revival Hey Tonight
Creedence Clearwater Revival I Heard It Through the Grapevine
Creedence Clearwater Revival I Put a Spell on You
Creedence Clearwater Revival Long As I Can See the Light
Creedence Clearwater Revival Midnight Special
Creedence Clearwater Revival Molina
Creedence Clearwater Revival Proud Mary
Creedence Clearwater Revival Someday Never Comes
Creedence Clearwater Revival Suzie Q
Creedence Clearwater Revival Up Around the Bend
Creedence Clearwater Revival Who'll Stop the Rain
Crosby, Stills & Nash Long Time Gone
Crosby, Stills & Nash Ohio
Crosby, Stills & Nash Suite: Judy Blue Eyes
Crosby, Stills & Nash Teach Your Children
Crosby, Stills, Nash & Young Carry On
Crowded House Don't Dream It's Over
Danger Danger Don’t Walk Away
Danzig Mother
Dave Matthews Band Crash into Me
David Bowie "Heroes"
David Bowie Absolute Beginners
David Bowie All the Young Dudes
David Bowie As The World Falls Down
David Bowie Ashes to Ashes
David Bowie Blue Jean
David Bowie Changes
David Bowie China Girl
David Bowie Fame
David Bowie Let's Dance
David Bowie Modern Love
David Bowie Rebel Rebel
David Bowie Sound and Vision
David Bowie Space Oddity
David Bowie Starman
David Bowie The Jean Genie
David Bowie The Man Who Sold the World
David Bowie The Stars (Are Out Tonight)
David Bowie Underground
David Bowie Young Americans
David Bowie Ziggy Stardust
David Bowie and Mick Jagger Dancing in the Street
David Bowie and Pat Metheny Group This Is Not America
David Coverdale Cry for Love
David Coverdale Don't You Cry
David Coverdale Love Is Blind
David Coverdale The Last Note of Freedom
David Coverdale Too Many Tears
David Lee Roth Goin' Crazy!
David Lee Roth Just Like Paradise
David Lee Roth Just a Gigolo
Dead Kennedys California Über Alles
Deep Blue Something Breakfast at Tiffany's
Deep Purple A Gypsy's Kiss
Deep Purple Anya
Deep Purple Black Night
Deep Purple Burn
Deep Purple Child in Time
Deep Purple Fireball
Deep Purple Highway Star
Deep Purple Hush
Deep Purple King of Dreams
Deep Purple Knocking at Your Back Door
Deep Purple Lazy
Deep Purple Mistreated
Deep Purple Perfect Strangers
Deep Purple Perfect Strangers
Deep Purple Smoke on the Water
Deep Purple Sometimes I Feel Like Screaming
Deep Purple Space Truckin'
Deep Purple Stormbringer
Deep Purple Strange Kind of Woman
Deep Purple This Time Around
Deep Purple Wasted Sunsets
Deep Purple Woman from Tokyo
Deep Purple You Keep on Moving
Def Leppard Animal
Def Leppard Bringin' On the Heartbreak
Def Leppard Foolin'
Def Leppard Hysteria
Def Leppard Let It Go
Def Leppard Let's Get Rocked
Def Leppard Photograph
Def Leppard Pour Some Sugar on Me
Def Leppard Pour Some Sugar on Me
Def Leppard Rock of Ages
Del Shannon Runaway
Depeche Mode Enjoy the Silence
Depeche Mode Personal Jesus
Depeche Mode Strangelove
Derek and the Dominos Layla
Detonautas Roque Clube Outro Lugar
Devo Time Out For Fun
Dexys Midnight Runners Come On Eileen
Dick Dale Misirlou
Dio All the Fools Sailed Away
Dio Dream On
Dio Holy Diver
Dio My Eyes
Dio Rainbow in the Dark
Dio Rock & Roll
Dio The Last in Line
Dion and the Belmonts Runaround Sue
Dire Straits Brothers in Arms
Dire Straits Lady Writer
Dire Straits Money for Nothing
Dire Straits Romeo and Juliet
Dire Straits So Far Away
Dire Straits Sultans of Swing
Dire Straits Sultans of Swing
Dire Straits Tunnel of Love
Dire Straits Walk of Life
Dire Straits Your Latest Trick
Dishwalla Charlie Brown’s Parents
Dishwalla Counting Blue Cars
Disturbed The Sound of Silence
Don McLean American Pie
Donovan Atlantis
Donovan Hurdy Gurdy Man
Donovan Mellow Yellow
Donovan Sunshine Superman
Dream Theater Another Day
Dream Theater Take Away My Pain
Duran Duran A View to a Kill
Duran Duran Notorious
Duran Duran Ordinary World
Duran Duran Save a Prayer
Eagle-Eye Cherry Save Tonight
Eagles Best of My Love
Eagles Desperado
Eagles Heartache Tonight
Eagles Hotel California
Eagles Life in the Fast Lane
Eagles Take It Easy
Eagles Tequila Sunrise
Echo & the Bunnymen Bedbugs and Ballyhoo
Echo & the Bunnymen Bring On the Dancing Horses
Echo & the Bunnymen Lips Like Sugar
Echo & the Bunnymen People Are Strange
Echo & the Bunnymen Rescue
Echo & the Bunnymen Silver
Echo & the Bunnymen The Cutter
Echo & the Bunnymen The Game
Echo & the Bunnymen The Killing Moon
Eddie Cochran Summertime Blues
Eddie Vedder Drive
Eddie Vedder Hard Sun
Eddie Vedder You've Got to Hide Your Love Away
Edwyn Collins A Girl Like You
Electric Light Orchestra Confusion
Electric Light Orchestra Hold on Tight
Electric Light Orchestra Last Train to London
Electric Light Orchestra Livin' Thing
Electric Light Orchestra Rock 'n' Roll Is King
Electric Light Orchestra Roll Over Beethoven
Elton John Bennie and the Jets
Elton John Crocodile Rock
Elton John Goodbye Yellow Brick Road
Elton John Lucy in the Sky with Diamonds
Elton John Philadelphia Freedom
Elton John Rocket Man
Elton John Your Song
Elvis Presley A Little Less Conversation
Elvis Presley All Shook Up
Elvis Presley Always on My Mind
Elvis Presley Blue Suede Shoes
Elvis Presley Blue Suede Shoes
Elvis Presley Can't Help Falling in Love
Elvis Presley Don't Be Cruel
Elvis Presley Heartbreak Hotel
Elvis Presley Hound Dog
Elvis Presley It’s Now or Never
Elvis Presley Jailhouse Rock
Elvis Presley Kiss Me Quick
Elvis Presley Love Me Tender
Elvis Presley My Way
Elvis Presley Suspicious Minds
Elvis Presley Tutti Frutti
Emerson, Lake & Palmer C'est la Vie
Emerson, Lake & Palmer From the Beginning
Emerson, Lake & Palmer Jerusalem
Emerson, Lake & Palmer Lucky Man
Emerson, Lake & Palmer Peter Gunn
Emerson, Lake & Palmer Tarkus
Engenheiros do Hawaii Infinita Highway
Eric Burdon & the Animals San Franciscan Nights
Eric Clapton After Midnight
Eric Clapton Bad Love
Eric Clapton Cocaine
Eric Clapton Forever Man
Eric Clapton Gotta Get Over
Eric Clapton I Can't Stand It
Eric Clapton I Shot the Sheriff
Eric Clapton Knockin' on Heaven's Door
Eric Clapton Lay Down Sally
Eric Clapton Layla
Eric Clapton Layla
Eric Clapton Tears in Heaven
Eric Clapton Tears in Heaven
Eric Clapton Wonderful Tonight
Europe Always the Pretenders
Europe Carrie
Europe The Final Countdown
Eurythmics Sweet Dreams (Are Made of This)
Eurythmics When Tomorrow Comes
Extreme Hole Hearted
Extreme More Than Words
Extreme Rest in Peace
Faces Ooh La La
Faces Stay with Me
Faith No More A Small Victory
Faith No More Easy
Faith No More Edge Of The World
Faith No More Epic
Faith No More Evidence
Faith No More Falling to Pieces
Faith No More From Out of Nowhere
Faith No More Midlife Crisis
Faith No More We Care a Lot
Fastway Say What You Will
Fats Domino Blueberry Hill
Fine Young Cannibals She Drives Me Crazy
Fine Young Cannibals Suspicious Minds
Fleetwood Mac Don't Stop
Fleetwood Mac Dreams
Fleetwood Mac Go Your Own Way
Fleetwood Mac Hold Me
Fleetwood Mac The Chain
Florence + the Machine Dog Days Are Over
Florence + the Machine Ship to Wreck
Focus Hocus Pocus
Focus House of the king
Focus Sylvia
Foghat Fool For the City
Foghat Ride, Ride, Ride
Foghat Slow Ride
Foghat Stone Blue
Foo Fighters All My Life
Foo Fighters Best of You
Foo Fighters Breakout
Foo Fighters Everlong
Foo Fighters Generator
Foo Fighters Learn to Fly
Foo Fighters My Hero
Foo Fighters Shame Shame
Foo Fighters The Pretender
Foo Fighters The Sky Is a Neighborhood
Foo Fighters Times Like These
Foreigner Cold as Ice
Foreigner Hot Blooded
Foreigner I Want to Know What Love Is
Foreigner Waiting for a Girl Like You
Four Tops Reach Out I'll Be There
Frank Zappa Be In My Video
Frank Zappa Bobby Brown
Frankie Valli Can't Take My Eyes Off You
Franz Ferdinand Take Me Out
Franz Ferdinand Walk Away
Freddie Mercury I Was Born to Love You
Free All Right Now
Free Wishing Well
Gang Gajang Gimme Some Lovin'
Garbage Only Happy When It Rains
Gary Glitter Rock and Roll Part 2
Gary Moore Still Got the Blues
Gary Moore Still Got the Blues
Gary Moore Still Got the Blues (For You)
Gary Numan Cars
Gary U.S. Bonds Quarter to Three
Gene Loves Jezebel Desire
Gene Vincent & His Blue Caps Be-Bop-a-Lula
Genesis Abacab
Genesis Dancing with the Moonlit Knight
Genesis Firth of Fifth
Genesis Follow You Follow Me
Genesis Home by the Sea
Genesis I Can't Dance
Genesis I Know What I Like (In Your Wardrobe)
Genesis Invisible Touch
Genesis Land of Confusion
Genesis Mama
Genesis Misunderstanding
Genesis No Reply at All
Genesis Paperlate
Genesis That's All
Genesis The Carpet Crawlers
Genesis The Musical Box
Genesis Throwing It All Away
Genesis Turn It On Again
George Harrison All Things Must Pass
George Harrison All Those Years Ago
George Harrison Dark Horse
George Harrison Give Me Love (Give Me Peace on Earth)
George Harrison Got My Mind Set on You
George Harrison My Sweet Lord
George Harrison What Is Life
George Thorogood & The Destroyers Bad to the Bone
George Thorogood & The Destroyers Who Do You Love?
Gerry Rafferty Baker Street
Gerry and the Pacemakers Don't Let the Sun Catch You Crying
Ghost Dance Macabre
Ghost He Is
Ghost If You Have Ghosts
Ghost Mary on a Cross
Ghost Square Hammer
Golden Earring Radar Love
Golpe de Estado Caso Sério
Goo Goo Dolls Before It's Too Late
Goo Goo Dolls Iris
Gorilla Clint Eastwood
Gorillaz Feel Good Inc.
Gotthard Anytime Anywhere
Gotthard Hush
Grand Funk Railroad Bad Time
Grand Funk Railroad Footstompin´music
Grand Funk Railroad Heartbreaker
Grand Funk Railroad Paranoid
Grand Funk Railroad Rock 'N Roll Soul
Grand Funk Railroad Sally
Grand Funk Railroad Some Kind of Wonderful
Grand Funk Railroad The Loco-Motion
Grand Funk Railroad We're an American Band
Green Day American Idiot
Green Day Basket Case
Green Day Boulevard of Broken Dreams
Green Day Geek Stink Breath
Green Day Good Riddance (Time of Your Life)
Green Day Holiday
Green Day Jesus of Suburbia
Green Day Oh Yeah!
Green Day Revolution Radio
Green Day She
Green Day Wake Me Up When September Ends

In [1]:
import pandas as pd
df2 = pd.read_csv('youtube.csv')
df2

,Artista,Musica,Observacao,SongID,YT
0,"10,000 Maniacs",More Than This,NaN,"10,000 Maniacs — More Than This — nan",hYMTmm5wR3U
1,10cc,I'm Not in Love,NaN,10cc — I'm Not in Love — nan,STugQ0X1NoI
2,10cc,Rubber Bullets,NaN,10cc — Rubber Bullets — nan,17GCBtKYaOg
3,3 Doors Down,Here Without You,NaN,3 Doors Down — Here Without You — nan,NxBl_q_NDas
4,3 Doors Down,Kryptonite,NaN,3 Doors Down — Kryptonite — nan,UjWZGLi-1jM
...,...,...,...,...,...
2218,ZZ Top,La Grange,NaN,ZZ Top — La Grange — nan,bSt4myecN_c
2219,ZZ Top,Legs,NaN,ZZ Top — Legs — nan,rM_nGN_du84
2220,ZZ Top,Rough Boy,NaN,ZZ Top — Rough Boy — nan,xUzeZXRaoBc
2221,ZZ Top,Sharp Dressed Man,NaN,ZZ Top — Sharp Dressed Man — nan,83ji4HioauM
2222,a-ha,Take On Me,NaN,a-ha — Take On Me — nan,HzdD8kbDzZA

In [5]:
i = 1400

In [87]:
i = i + 10
import webbrowser
urls = df2[i:i+10]
display(urls)
for _, u in urls.iterrows():
    # Define the URL to open
    url = "https://www.youtube.com/watch?v=" + u['YT']

    # Open the URL in the default web browser
    webbrowser.open(url)

print(i)

,Artista,Musica,Observacao,SongID,YT
2220,ZZ Top,Rough Boy,NaN,ZZ Top — Rough Boy — nan,xUzeZXRaoBc
2221,ZZ Top,Sharp Dressed Man,NaN,ZZ Top — Sharp Dressed Man — nan,83ji4HioauM
2222,a-ha,Take On Me,NaN,a-ha — Take On Me — nan,HzdD8kbDzZA

2220